name: _
publish_to: none

environment:
  sdk: '^3.8.0'

workspace:
  - gyanburu_fin_client
  - gyanburu_fin_server
  - gyanburu_fin_flutter
dependency_overrides:
  flutter_secure_storage: ^10.0.0
dependencies:
  http: ^1.6.0

